/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.css.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CSSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return nl.dslmeinte.xtext.css.ui.internal.CSSActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return nl.dslmeinte.xtext.css.ui.internal.CSSActivator.getInstance().getInjector("nl.dslmeinte.xtext.css.CSS");
	}
	
}
